multiplexed:       false
sample_name:       "SAMPLE_NAME"
barcodes:          "BC01 BC02 BC03"
reference:         "data/reference/NC_000962.3.fa.gz"
container:         "containers/tb.simg"
plot_downsampling: 25000
max_covg:          150  # samples with more coverage than this will be downsampled
#Available barcoding kits are:
#  EXP-NBD103
#  EXP-NBD104
#  EXP-NBD114
#  EXP-NBD196
#  EXP-PBC001
#  EXP-PBC096
#  OND-SQK-LP0096M
#  OND-SQK-LP0096S
#  OND-SQK-LP0768L
#  OND-SQK-RP0096M
#  OND-SQK-RP0384L
#  SQK-16S024
#  SQK-LWB001
#  SQK-NBD110-24
#  SQK-NBD110-96
#  SQK-PBK004
#  SQK-PCB109
#  SQK-RAB201
#  SQK-RAB204
#  SQK-RBK001
#  SQK-RBK004
#  SQK-RBK096
#  SQK-RLB001
#  SQK-RPB004
#  VSK-VMK001
#  VSK-VMK002
# To use multiple kits, separate them by spaces and place in quotes. For example
# kit: '"EXP-NBD104 EXP-NBD114"'
kit:               "EXP-NBD104"
