multiplexed: false
sample_name: "SAMPLE_NAME"
barcodes: "BC01 BC02 BC03 BC04 BC05"
reference: "data/reference/NC_000962.3.fa.gz"
#container: "containers/tb.simg"
container: "docker://quay.io/iqballab/mykrobe_tb_workflow"
plot_downsampling: 50000
#Available barcoding kits are:
#  EXP-NBD103
#  EXP-NBD104
#  EXP-NBD114
#  EXP-NBD196
#  EXP-PBC001
#  EXP-PBC096
#  OND-SQK-LP0096M
#  OND-SQK-LP0096S
#  OND-SQK-LP0768L
#  OND-SQK-RP0096M
#  OND-SQK-RP0384L
#  SQK-16S024
#  SQK-LWB001
#  SQK-NBD110-24
#  SQK-NBD110-96
#  SQK-PBK004
#  SQK-PCB109
#  SQK-RAB201
#  SQK-RAB204
#  SQK-RBK001
#  SQK-RBK004
#  SQK-RBK096
#  SQK-RLB001
#  SQK-RPB004
#  VSK-VMK001
#  VSK-VMK002
# To use multiple kits, separate them by spaces and place in quotes. For example
# kit: '"EXP-NBD104 EXP-NBD114"'
kit: "EXP-NBD104"
