multiplexed: false
sample_name: "SAMPLE_NAME"
barcodes: "BC01 BC02 BC03 BC04 BC05"
basecall: true

flowcell: "FLO-MIN106"
kit: "SQK-LSK108"

reference: "data/reference/NC_000962.3.fa.gz"

containers:
    albacore: "/nfs/leia/research/iqbal/mbhall/Software/Singularity_images/Basecallers/albacore.simg"
    nanoporeqc: "/nfs/leia/research/iqbal/mbhall/Software/Singularity_images/nanoporeqc.simg"
